puts "🌱 Seeding sweet living data..."

puts "🔑 Creating buyers..."
b1 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b2 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b3 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b4 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b5 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b6 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b7 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b8 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b9 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b10 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b11 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b12 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b13 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b14 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b15 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b16 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b17 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b18 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b19 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b20 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b21 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b22 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b23 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b24 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")
b25 = Buyer.create(username: Faker::Name.name, email: Faker::Name.first_name + "@gmail.com")

puts "🔑 Buyers created successfully"

#create data for table Seller
puts "👨‍💼 creating sellers..."
s1 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s2 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s3 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s4 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s5 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s6 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s7 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s8 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s9 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s10 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s11 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s12 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s13 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s14 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s15 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s16 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s17 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s18 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s19 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s20 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s21 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s22 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s23 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s24 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)
s25 = Seller.create(username: Faker::Name.name, email: Faker::Name.first_name+ "@gmail.com", phone_number: Faker::PhoneNumber.phone_number)

puts "👨‍💼 Seller created successfully"

#create data for table Property
puts "🏣 Creating properties..."

Property.create({houses: "2bd|2ba|1300sqft", image_url: "https://i.postimg.cc/0Qvt8X0G/house1.jpg", price: 10.4, location: "Syokimau", number_of_rooms: 3, description: "Unique Craftsman in coveted neighborhood 2 blocks from Lowman Beach and Lincoln Park. Secluded front porch. Main floor has 2 bedrooms and full bath with claw foot tub. Large kitchen w/high end cabinets, granite counters, marble tile and stainless appliances. Miele 5 burner gas cooktop and Miele d/w plus a warming drawer. Sweeping cherry wood stairway to upper floor bedrooms, laundry, large primary brm with in-suite bathroom, recessed lighting and step in closet. Finished attic room! The backyard features large patio, mature garden, vegetable garden space, pond and small fountain. Walk in cellar provides loads of storage & freezer space. Alley access, 2+car garage w/upper bonus room and sitting deck. Trailer/RV pad w/full hook-ups and drain.", category: "house", seller_id: s1.id, buyer_id: b3.id })  
Property.create(houses: "3bd|2.75ba|1500sqft", image_url: "https://i.postimg.cc/Sx8jWgcz/image-3.jpg", price: 20.6, location: "Parklands Road,Westlands", number_of_rooms: 2, description: "Qualifying Veterans may assume 3.25% $586,000 VA loan! This well-appointed home perches proudly over the neighborhood & features hemlock craftsman style molding & paneled interior doors. Spacious & bright, this home boosts Central A/C, 4 Bedrooms, 2.5 Bathrooms w/ granite slab countertops. The open floor plan is perfect for entertainig w/ beautiful hardwoods, vaulted ceilings & gas fireplace. The kitchen features granite slab counters, SS appliances, center island w/ seating maple cabinets w/ crown molding & pantry. Primary suite w/ huge closet & luxurious 5-piece en-suite w/soaking tub. Fenced backyard is an outdoor oasis w/patio & level garden space. This home is turnkey ready w/ laundry room, ample storage & even wired for generator." , category: "house", seller_id: s2.id, buyer_id: b5.id)
Property.create(houses: "3bd|2.75ba|1500sqft", image_url: "https://i.postimg.cc/MKnnG6T5/image-4.jpg", price: 40, location: "Riverside Drive,Kilimani", description: "Originally a 3 bedroom--two bedrooms have been joined into a large artist's studio. Keep as is or it can be easily restored. Primary bedroom has an attached bathroom and a nicely sized closet. Second bathroom is off the hallway. Fresh interior paint throughout. Covered porch is off the side door. It has a furnace, or you can use the pellet stove for those cozy winter nights. Minutes away from shopping and highways. Buyers need to be preapproved by the park. Washer and dryer hookups. New microwave and one-year-old fridge will transfer. Space rent is $860 and includes water and sewer. 1 year Home Warranty supplied by the seller. Seller is offering a $2,000 credit to the buyers for an acceptable offer before 12/31!", category: "house", number_of_rooms: 1, seller_id: s3.id, buyer_id: b12.id)
Property.create(houses: "3bd|2.75ba|1400sqft", image_url: "https://i.postimg.cc/qvCQ2HmX/image-28.jpg", price: 32.5, location: "Oloitoktok Road, Kileleshwa", description: "Originally a 3 bedroom--two bedrooms have been joined into a large artist's studio. Keep as is or it can be easily restored. Primary bedroom has an attached bathroom and a nicely sized closet. Second bathroom is off the hallway. Fresh interior paint throughout. Covered porch is off the side door. It has a furnace, or you can use the pellet stove for those cozy winter nights. Minutes away from shopping and highways. Buyers need to be preapproved by the park. Washer and dryer hookups. New microwave and one-year-old fridge will transfer. Space rent is $860 and includes water and sewer. 1 year Home Warranty supplied by the seller. Seller is offering a $2,000 credit to the buyers for an acceptable offer before 12/31!", category: "house", number_of_rooms: 4, seller_id: s4.id, buyer_id: b23.id)
Property.create(houses: "4bd|3.75ba|1700sqft", image_url: "https://i.postimg.cc/ZRTk5x8N/image-54.jpg", price: 36.5, location:"Kindaruma Road,Kilimani", description: "NEW Furnace with A/C, NEW Gas Fireplace Insert, NEW Kitchen!This updated and meticulously cared for 3 bedroom rambler offers easy access to I-5 and I-405 while being located in a quiet coul de sac.Newly remodeled kitchen with ceramic tile floors, quartz countertops, and new microwave, range, and refrigerator. Fully fenced backyard features a deck, fire pit and shed.Close to schools, Alderwood Mall, bus line, and Lynnwood Light Rail when extension is completed in 2024!", category: "house" , number_of_rooms: 5, seller_id: s6.id, buyer_id: b4.id)
Property.create(houses: "3bd|2.75ba|200sqft", image_url: "https://i.postimg.cc/YqPb4CxC/image-45.jpg", price: 37.5, location:"Matasia, Ngong", description:"One of Washington's finest gated senior living communities SUNRISE EAST Manufactured Home Community! Clubhouse, swimming pool, hot tub, exercise room, putting green and don't forget to challenge a billiards game. Don't forget RV parking and storage area. You will appreciate the open floor plan and a covered patio off the extra room. Spacious primary suite and primary bath provide room enough for your bedroom furniture. Propane fireplace in extra room. Vinyl planking flooring primary bath and extra room. Soft water tank stays - not used.", category: "house", number_of_rooms: 6, seller_id: s5.id, buyer_id: b7.id)
Property.create(houses: "3bd|35ba|1800sqft", image_url: "https://i.postimg.cc/HnhF3Gf0/image-52.jpg", price: 45.5, location:"Karen Road,Karen", description:"This captivating 3-bedroom, 2.5-bathroom Classic Tri-level is found in quiet, highly desireable area. The home is convenient to schools and parks and is an easy commute to Military Bases. The large, private back yard is perfect for beverages & conversation. The interior welcomes you with oak hardwoods in foyer, kitchen and living spaces and a gas fireplace in the living room. Expansive kitchen charms with attractive L-shaped layout and dining nook. The highly functional primary bedroom includes recent updates, a walk-in closet, and private bath with step-in shower. All bedrooms are large with ample closet space. Downstairs doubles as home office & rec room. Attached two-car garage. Someone's going to be very happy here . . . let it be you!", category: "house", number_of_rooms: 7, seller_id: s7.id, buyer_id: b21.id)
Property.create(houses: "4bd|3.75ba|2000sqft", image_url: "https://i.postimg.cc/QMGmbYwL/image-46.jpg", price: 38.5, location:"Isinya", description:"Charming Rucker Hill home w/updated finishes & original classic window frames, doors & more. 2 bedrm, 1.75 bath w/full unfinished basement & half story attic area that could be finished into additional living areas. Both areas have tall ceilings. Updated electrical & plumbing, gas FA heat & on demand hot water. Beautiful Acacia hardwood floors in living room & kitchen. Tile floors in Family rm w/gas fireplace also great for dining area & access to back patio. Both bath rms have been updated & have heated tile floors! The kitchen has also been updated w/granite counter tops, appliances & newer cabinets. Mountain views from upstairs, living rm & primary bedroom. Patio w/hot tub, nice back yard, 2 car garage & RV parking. Must See!", category: "house", number_of_rooms: 7, seller_id: s8.id, buyer_id: b22.id)
Property.create({houses: "4bd|4ba|200sqft", image_url: "https://i.postimg.cc/L65x61LW/image-47.jpg", price: 70.5, location:"Muthaiga", description:"Ultimate turn-key home at The Lookout! The BlueWater is situated on Vineyard Park just steps away from the new, year-round Lookout Pool. Expansive 2,952sf home features 4bd/4.5bth + bonus room; sleeps 20 w/ exceptional rental income. This rustic farmhouse features high-end finishes & furnishings throughout including shiplap walls, Restoration Hardware vanities, kitchen island & dining room table & Pottery Barn lighting & furnishings throughout. Incredible outdoor living area has a classic wraparound porch w/ outdoor seating, dining area, fire pit, sun sail trellis, BBQ & private hot tub. The Lookout offers community waterfront, marina, parks, pools, sports courts & more. Superb VACATION HOME RENTAL w/ on-site management/hospitality.", category: "house", number_of_rooms: 3, seller_id: s9.id, buyer_id: b6.id})  
Property.create(houses: "3bd|2.75ba|2000sqft", image_url: "https://i.postimg.cc/1tMKymtP/image-30.jpg", price: 35.5, location:"Juja Road, Juja", description:"OPPORTUNITY KNOCKS! Fantastic five-bedroom home in heart of Everett! Spacious and bright, this sparkling clean two-story is complete with new roof, oak hardwood floors, granite countertops, stainless steel appliances and more! Natural gas heat and wood burning fireplace keep things cozy. Upstairs has its own separate entrance and SECOND KITCHEN great for guests or possible duplex! Tons of space with fully finished basement area. Detached fully finished 360SF structure would make a great office, workspace or? City and mountain views in convenient Riverside neighborhood just minutes from downtown. Make this yours today!", category: "house", number_of_rooms: 2, seller_id: s10.id, buyer_id: b17.id)
Property.create(houses: "3bd|2.75ba|1700sqft", image_url: "https://i.postimg.cc/vBXJgxhN/image-50.jpg", price: 40.5, location:"Langata Road, Karen", description:"Meticulously maintained 3 bedrooms and 2.75 bathrooms Kelsey Creek home! Remodeled in 2012 and refreshed in 2022 with beautiful kitchen features granite counter tops, newer range/oven, microwave & hardwood flrs thru out. Newer bathrooms, newer carpets, interior paint, newer light fixtures and A/C. Master bed w/ HUGE walk-in closets & newer master bath. Lower level has recreational/hobby room, office and storage. Multi-level refinished deck & fully fenced flat backyard. Close to freeway, mins to Downtown Bellevue District. One block from the Bellevue International School. Award winning Bellevue school District.", category: "house", number_of_rooms: 1, seller_id: s11.id, buyer_id: b19.id)
Property.create(houses: "3bd|2.75ba|1800sqft", image_url: "https://i.postimg.cc/nLKbxPDZ/image-53.jpg", price: 52.5, location:"Gigiri", description:"Park like setting and full of natural light, this older home has huge spaces for all your hobbies, plus the possibility to run your business at the same location with a private office entry. A beautiful flowering dogwood welcomes you at the dutch door entry while the kitchen has loads of cabinets and unique antler hardware. Several fireplaces offer that warm cozy feeling. Basement is a blank slate - make it your own. You'll appreciate all that this unique site has to offer - over 6000 square feet in covered outbuilding space and great visibility on Highway 12. Please be considerate and make an appointment at least 2 hours in advance as pets will need to be secured.", category: "house", number_of_rooms: 4, seller_id: s12.id, buyer_id: b3.id)
Property.create(houses: "3bd|2.75ba", image_url: "https://i.postimg.cc/d1ySzQL1/image-10.jpg", price: 65000, location:"South C", description:"OPPORTUNITY KNOCKS! Fantastic five-bedroom home in heart of Everett! Spacious and bright, this sparkling clean two-story is complete with new roof, oak hardwood floors, granite countertops, stainless steel appliances and more! Natural gas heat and wood burning fireplace keep things cozy. Upstairs has its own separate entrance and SECOND KITCHEN great for guests or possible duplex! Tons of space with fully finished basement area. Detached fully finished 360SF structure would make a great office, workspace or? City and mountain views in convenient Riverside neighborhood just minutes from downtown. Make this yours today!",category: "apartment", number_of_rooms: 5, seller_id: s13.id, buyer_id: b10.id)
Property.create(houses: "3bd|2.75ba", image_url: "https://i.postimg.cc/mkW6RxHS/image-9.jpg", price: 65000, location:"South B", description:"This captivating 3-bedroom, 2.5-bathroom Classic Tri-level is found in quiet, highly desireable area. The home is convenient to schools and parks and is an easy commute to Military Bases. The large, private back yard is perfect for beverages & conversation. The interior welcomes you with oak hardwoods in foyer, kitchen and living spaces and a gas fireplace in the living room. Expansive kitchen charms with attractive L-shaped layout and dining nook. The highly functional primary bedroom includes recent updates, a walk-in closet, and private bath with step-in shower. All bedrooms are large with ample closet space. Downstairs doubles as home office & rec room. Attached two-car garage. Someone's going to be very happy here . . . let it be you!", category: "apartment", number_of_rooms: 6, seller_id: s14.id, buyer_id: b24.id)
Property.create(houses: "3bd|2.75ba", image_url: "https://i.postimg.cc/zvT6RDrM/image-58.jpg",price: 90000, location:"Dennis Pritt Road, Kilimani", description:"MLS#2027281 Do your chores keep you from living your best life? Stop Spending Time Mowing That Huge Yard! If this is you, you don't want to miss this home. Less lawn to mow, you have more time to host football games in your open kitchen/great room. Bedrooms are tucked around the corner for those who do not wish to partake. Don't want to cook? Just up the street are some great restaurants. Catch Southridge on the field? That's just a few minutes walk too! Parks, shopping, restaurants, bike paths, golf, lots of schools & so much more right out your front door. Showings start soon so contact an agent for more information!", category: "apartment", number_of_rooms: 7, seller_id: s15.id, buyer_id: b25.id)
Property.create(houses: "2bd|1.75ba", image_url: "https://i.postimg.cc/02qL1SGq/image-56.jpg", price: 85000, location:"Waiyaki Way, Westlands", description:"Model Home Available in The New 33 Home Community close to Silverdale. The 2259 SQ Ft Plan features 4 Bedrooms 2.5 Baths. Kitchen with walk-in Pantry opens into Dining area and Great Room. Off the Dining area is a covered back Patio for year round BBQ. Den/Office on main floor. Upstairs features Primary Bedroom with 5 piece Bath and a large Walk-In Closet, plus 3 other bedrooms and a large Loft Area. Homes come with a Heating/Cooling System. Incredible Financing Options with Preferred Lender. Central Kitsap School District! Close to Kitsap Mall and easy access to Hwy 3. Great Location for either Military Base, and Shipyard. Minutes from Ferry. Ready for your customized finishes. For GPS use 677 NE Waaga Way.", category: "apartment", number_of_rooms: 7, seller_id: s16.id, buyer_id: b22.id)
Property.create({houses: "3bd|2.75ba", image_url: "https://i.postimg.cc/ry4vHjrJ/image-55.jpg", price: 106000, location: "Kirawa Road, Kitisuru", description: "Puget Sound waterfront living for the discerning entertainer & hobbyist, this home features timeless finishes, inspiring vistas & ample space for hosting, tinkering & living well. Unobstructed mountain & sound views from each of the 3 levels overlook a terraced lot (a gardener’s dream w/irrigated beds & greenhouse) & 63’ of low bank waterfront. Gourmet kitchen w/stainless steel appliances & vast granite counters flows into dining & 2 living rooms; plus a home office & wine cellar. A sanctuary of a primary suite offers an oversized closet, spa-like 5 piece bath & fitness room. The additional 2 beds each have their own bath; a 3rd living space is the ideal media room. Garage parking for 4 cars, plus all the storage you'd ever need.", category: "apartment", number_of_rooms: 3, seller_id: s17.id, buyer_id: b17.id})  
Property.create(houses: "3bd|3.75ba", image_url: "https://i.postimg.cc/yYX21Nn3/image-57.jpg", price: 100000, location:"Kingara Road, Lavington", description:"Don’t miss this gorgeous 3-bedroom end-unit townhome in the sought-after Northpointe community of Mill Creek. Looks, feels, and lives like a single-family home. You’ll feel a sense of arrival at the covered front porch, leading straight into the main level (no flight of stairs @ entry!). Main level boasts a spacious living room, beautiful kitchen with granite counters, stainless appliances, eating bar, and private patio– perfect for entertaining. Abundant natural light throughout. Upstairs you’ll find a generously sized primary bedroom with a view of Exploration Park, 5-piece ensuite bath + walk-in closet. Attached 2 car garage, community park, and located close to Mill Creek Town Center. Highly rated schools. Welcome home!", category: "apartment", number_of_rooms: 2, seller_id: s18.id, buyer_id: b25.id)
Property.create(houses: "4bd|3ba", image_url: "https://i.postimg.cc/sgjqvR06/image-49.jpg", price: 60000, location:"Thindigua", description:"Welcome to The Elements on Dexter, sited in the highly sought-after neighborhood of Queen Anne. Be a part of the booming, ultra-dynamic & new technology district. The Elements on Dexter are just steps from Lake Union & only minutes to the bustling Fremont, Queen Anne & South Lake Union,making these stately residences both distinctive and highly desirable. Offering a variety of FP from, 1,228-1,600+ SF. Residences provide functional living spaces,floor-to-ceiling windows, designer kitchens with high-end appliances, private terraces with dramatic views & epic sunrises that will frame the active vista of seaplanes, kayaks & sailboats year-round. Enjoy the lushly green tech savvy courtyard ~SECURED UNDERGROUND GARAGE~ w/private storage.", category: "apartment", number_of_rooms: 1, seller_id: s19.id, buyer_id: b15.id)
Property.create(houses: "3bd|2ba", image_url: "https://i.postimg.cc/Mp94BrCW/image-44.jpg", price: 62000, location:"Kiambu Road", description:"Pride in ownership shows in this move-in ready 3 bed 2.25 bath tri-level home. Nestled back from the street, vaulted ceilings greet you upon entry. Natural east and west facing light floods the tastefully updated home. Thoughtful layout between the living room, dining room and remodeled kitchen on the main level. A few steps down take you to the family room that beckons movie nights by the gas fireplace. Retreat to the master bedroom upstairs with en-suite bath. Two additional bedrooms and 1.5 baths mean room for everyone. Incredible patio, deck and grounds call for entertaining or simply relaxing. New roof, furnace, hot water heater 2018, A/C 2022. Mukilteo schools and walking distance to Lake Serene make this a must see!", category: "apartment", number_of_rooms: 4, seller_id: s20.id, buyer_id: b23.id)
Property.create(houses: "3bd|2ba", image_url: "https://i.postimg.cc/j5wGtQkR/image-33.jpg", price: 63000, location:"Roasters,Thika Road", description:"Puget Sound waterfront living for the discerning entertainer & hobbyist, this home features timeless finishes, inspiring vistas & ample space for hosting, tinkering & living well. Unobstructed mountain & sound views from each of the 3 levels overlook a terraced lot (a gardener’s dream w/irrigated beds & greenhouse) & 63’ of low bank waterfront. Gourmet kitchen w/stainless steel appliances & vast granite counters flows into dining & 2 living rooms; plus a home office & wine cellar. A sanctuary of a primary suite offers an oversized closet, spa-like 5 piece bath & fitness room. The additional 2 beds each have their own bath; a 3rd living space is the ideal media room. Garage parking for 4 cars, plus all the storage you’d ever need.", category: "apartment", number_of_rooms: 5, seller_id: s21.id, buyer_id: b7.id)
Property.create(houses: "3bd|2ba", image_url: "https://i.postimg.cc/pTw3Thgz/image-32.jpg", price: 55000, location:"Mombasa Road,Imara Daima", description:"One of Washington's finest gated senior living communities SUNRISE EAST Manufactured Home Community! Clubhouse, swimming pool, hot tub, exercise room, putting green and don't forget to challenge a billiards game. Don't forget RV parking and storage area. You will appreciate the open floor plan and a covered patio off the extra room. Spacious primary suite and primary bath provide room enough for your bedroom furniture. Propane fireplace in extra room. Vinyl planking flooring primary bath and extra room. Soft water tank stays - not used.", category: "apartment", number_of_rooms: 6, seller_id: s22.id, buyer_id: b24.id)
Property.create(houses: "3bd|2ba", image_url: "https://i.postimg.cc/wB3rQQzD/image-31.jpg", price: 58000, location:"Nyayo Estate, Mombasa Road", description:"Tranquil Setting on the Cedar River! Enjoy trails along the river and easy access to dining and downtown. Turn-Key lock and go home. Close to Golf facility, The Landing, and Coulon Beach Park. It's the perfect home in the heart of the city but feels tucked away. This wonderful 2 Bedroom 1 3/4 Bathroom Home provides Views of the Cedar River from the Living Area and Both Bedrooms. Newly Remodeled Beautiful Bathrooms, New Water Heater, and New Carpet! Kitchen counter eating space, Cozy Fireplace, Balcony off of the Living Area (also a view!), and W/D in the unit. Secure Garage Parking and Private Storage. Bonus-Elevator for easy unit access! Don't miss the Community Garden on the north side of the river.", category: "apartment", number_of_rooms: 7, seller_id: s23.id, buyer_id: b5.id)
Property.create(houses: "3bd|2ba", image_url: "https://i.postimg.cc/pTw3Thgz/image-32.jpg", price: 58000, location:"Nyayo Estate, Mombasa Road", description:"Just blocks from Ballard's best: its year-round farmer's market, groceries, restaurants, hardware stores, boutiques and more--All just steps from your front door! Experience amazing morning sunlight and the twinkling lights at night of the Ballard and Ship Canal Bridges from your living room, bedroom, or balcony, and even see Mt. Rainier on a clear day! Located in downtown Ballard, this gorgeous condo offers its residents gorgeous views, impeccable interiors, and all while being just steps from everything Ballard has to offer. Including a balcony, storage unit and included parking-space, this condominium gives residents luxe living in the heart of Ballard.", category: "apartment", number_of_rooms: 5, seller_id: s24.id, buyer_id: b17.id)


puts "🏤 Properties created successfully"

puts "🌱 seeding done!!"